# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/guide/topics/configure_build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See also
# http://www.gradle.org/guide/topics/configure_build_environment/the_gradle_daemon.html
# org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/guide/topics/configure_build_environment/the_gradle_daemon.html
# org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true

# Windows Cross-Drive Build Fix
org.gradle.jvmargs=-Xmx4g
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
